version: 0.2
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
            - a=$(date "+%Y%m%d%H%M%S")
            - aws ec2 create-image --instance-id i-090ffb35156dbd4eb --name "AMI_$a" --description "An AMI for my server" --no-reboot          
artifacts:
  files:
    - '**/*'
    - 'appspec.yml'
